### ISSUE TITLE
Problem: The Automation Tools AMClient script could be easier to jump into and add functionality

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/automation-tools#47]
As a developer I like to be able to see a division in responsibilities of code. For example being able to see clearly where I can add new CLI args, or new logic.

The AMClient.py script in Automation Tools currently tries to do a lot of this in a single script - args/logging/functional logic. I think there is an opportunity to pull those three pieces apart to make it easier for developers to work with and open the opportunity for smaller refactors in the future. 

AMClient.py is a good candidate to have this attention paid to it as its functionality is only likely to grow as it wraps the AM API capabilities in a consistent way. 

**Proposal:**

* Create a logging configuration script that can provide a model for sharing across the other Automation Tools (Transfer.py would be the first to make use of this)
* Separate the CLI argument definitions into a script on its own so that it becomes an entry point for new functionality being added by developers.
* Leave the core features of the script in place (API calls and handling) and import the new scripts at the module level.

This will reduce the size of each of the scripts and hopefully make it a bit easier for folk to delve into.

**Comment by sevein** [comment]
During your endeavor please try to keep in mind that this repo doesn't follow Python's best practices and people is going to expect that things keep working as usually, i.e. clone the repo and use it as it was described in the [installation instructions](https://github.com/artefactual/automation-tools#installation), files like `transfers/transfer.py` are executables and this should probably keep being this way unless we decide to break the contract. Sounds like #46 doesn't really change it so that's great.

I think that we need a long-term plan that serves as basis for future efforts like #46. To be clear, I like #46 but I'm also wondering if the next effort should be previously discussed. I personally like the way that https://github.com/docker/compose is arranged and I think that it'd be awesome that automation-tools moves into that direction.

**Comment by ross-spencer** [comment]
Closed via 699b018
